### ISSUE TITLE
TODO List Before paper

### ISSUE THREAD

**Issue by MKrbm** [MKrbm/worms#18]
This issue tracks the implementation of pending enhancements in our rms project. 

- [x] Implement `mes` method for enhanced simulation accuracy.
   - Doing in #23 
- [x] Calculate optimized unitary for the Heisenberg model in various parameter regions.
- [x] Address and resolve the zero_worm bug, ensuring consistency with previous correct results.
  - This will be delt by [issue](https://github.com/MKrbm/worms/issues/19#issue-2030946190) 
- [x] Implement test to check the simulation is correct
  - Use HPhi to validate `solver_torch` is correct
  -  Then, use `solver_torch` to check `worm` is correct.
  - Tracked with [issue](https://github.com/MKrbm/worms/issues/21#issue-2031187625)

**Comment by MKrbm** [comment]
Additionaly
- [ ] Device riemannian optimization for special linear group
- [ ] Read into the BLBQ1D paper about what unitary matrix can remove negative sign
- [ ] Come up with better algorithm to optimizate unitary matrix. Currently it falls into local minimum too frequently

## About Thesis
### Introduction part (QMC)
- [ ] Explain deeper about worm algorithm for HXXX model
- [ ] How to observ two point correlation
- [ ] About negative sign problem
- [ ] How to remove negative sign?

## Figure
- [ ] Select some parameters and run simulation on these parameters agains system size / temperature (fixing temperature / system size) #22 
- [ ]  Prepare table to compare worm result and analytical result
    - AKLT
    - MG
    - SS

**Comment by MKrbm** [comment]
It turned out optimized solution for BLBQ1D was not the same as analytical one, and what is worse, ground states are four-fold degenerated and will not provide average sign 1 in zero temperature.
